QuickLMSbaseBuild/routes/web.php
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('courses', 'Admin\CoursesController');
    Route::post('courses_mass_destroy', ['uses' => 'Admin\CoursesController@massDestroy', 'as' => 'courses.mass_destroy']);
    Route::post('courses_restore/{id}', ['uses' => 'Admin\CoursesController@restore', 'as' => 'courses.restore']);
    Route::delete('courses_perma_del/{id}', ['uses' => 'Admin\CoursesController@perma_del', 'as' => 'courses.perma_del']);
    Route::resource('lessons', 'Admin\LessonsController');
    Route::post('lessons_mass_destroy', ['uses' => 'Admin\LessonsController@massDestroy', 'as' => 'lessons.mass_destroy']);
    Route::post('lessons_restore/{id}', ['uses' => 'Admin\LessonsController@restore', 'as' => 'lessons.restore']);
    Route::delete('lessons_perma_del/{id}', ['uses' => 'Admin\LessonsController@perma_del', 'as' => 'lessons.perma_del']);
    Route::resource('questions', 'Admin\QuestionsController');
    Route::post('questions_mass_destroy', ['uses' => 'Admin\QuestionsController@massDestroy', 'as' => 'questions.mass_destroy']);
    Route::post('questions_restore/{id}', ['uses' => 'Admin\QuestionsController@restore', 'as' => 'questions.restore']);
    Route::delete('questions_perma_del/{id}', ['uses' => 'Admin\QuestionsController@perma_del', 'as' => 'questions.perma_del']);
    Route::resource('questions_options', 'Admin\QuestionsOptionsController');
    Route::post('questions_options_mass_destroy', ['uses' => 'Admin\QuestionsOptionsController@massDestroy', 'as' => 'questions_options.mass_destroy']);
    Route::post('questions_options_restore/{id}', ['uses' => 'Admin\QuestionsOptionsController@restore', 'as' => 'questions_options.restore']);
    Route::delete('questions_options_perma_del/{id}', ['uses' => 'Admin\QuestionsOptionsController@perma_del', 'as' => 'questions_options.perma_del']);
    Route::resource('tests', 'Admin\TestsController');
    Route::post('tests_mass_destroy', ['uses' => 'Admin\TestsController@massDestroy', 'as' => 'tests.mass_destroy']);
    Route::post('tests_restore/{id}', ['uses' => 'Admin\TestsController@restore', 'as' => 'tests.restore']);
    Route::delete('tests_perma_del/{id}', ['uses' => 'Admin\TestsController@perma_del', 'as' => 'tests.perma_del']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');

    Route::get('/canned', ['uses' => 'Admin\CannedController@index', 'as' => 'admin.canned.index']);
    Route::get('/classroom', ['uses' => 'Admin\ClassroomController@index', 'as' => 'admin.classroom.index']);
    Route::get('/messages', ['uses' => 'Admin\MessagingController@index', 'as' => 'admin.messages.index']);
    Route::get('/tmessages', ['uses' => 'Admin\TMessagingController@index', 'as' => 'admin.tmessages.index']);
    Route::get('/notification', ['uses' => 'Admin\NotificationsController@index', 'as' => 'admin.notification.index']);
    Route::get('/trainee', ['uses' => 'Admin\TraineeController@index', 'as' => 'admin.trainee.index']);
    Route::get('/trainer', ['uses' => 'Admin\TrainerController@index', 'as' => 'admin.trainer.index']);
    Route::get('/trainerhome', ['uses' => 'Admin\TrainerhomeController@index', 'as' => 'admin.trainerhome.index']);

    Route::resource('/canned', 'Admin\CannedController');
    Route::resource('/classroom', 'Admin\ClassroomController');
    Route::resource('/messages', 'Admin\MessagingController');
    Route::resource('/tmessages', 'Admin\TMessagingController');
    Route::resource('/notification', 'Admin\NotificationsController');
    Route::resource('/trainee', 'Admin\TraineeController');
    Route::resource('/trainer', 'Admin\TrainerController');
    Route::resource('/trainerhome', 'Admin\TrainerhomeController');

});


 Route::get('/admin/trainer_review', 'Admin\TrainerController@trainer_review')->name('admin.trainer_review.index');

    // Route::get('/admin/canned', ['uses' => 'Admin\CannedController@index', 'as' => 'admin.canned.index']);
    // Route::get('/admin/classroom', ['uses' => 'Admin\ClassroomController@index', 'as' => 'admin.classroom.index']);
    // Route::get('/admin/messages', ['uses' => 'Admin\MessagingController@index', 'as' => 'admin.messages.index']);
    // Route::get('/admin/tmessages', ['uses' => 'Admin\TMessagingController@index', 'as' => 'admin.tmessages.index']);
    // Route::get('/admin/notification', ['uses' => 'Admin\NotificationsController@index', 'as' => 'admin.notification.index']);
    // Route::get('/admin/trainee', ['uses' => 'Admin\TraineeController@index', 'as' => 'admin.trainee.index']);
    // Route::get('/admin/trainer', ['uses' => 'Admin\TrainerController@index', 'as' => 'admin.trainer.index']);
    // Route::get('/admin/trainerhome', ['uses' => 'Admin\TrainerHomeController@index', 'as' => 'admin.trainerhome.index']);


    // Route::get('/admin/canned', 'Admin\CannedController@index')->name('admin.canned.index');
    // Route::get('/admin/classroom', 'Admin\ClassroomController@index')->name('admin.classroom.index');
    // Route::get('/admin/messages', 'Admin\MessagingController@index')->name('admin.messages.index');
    // Route::get('/admin/tmessages', 'Admin\TMessagingController@index')->name('admin.tmessages.index');
    // Route::get('/admin/notification', 'Admin\NotificationsController@index')->name('admin.notification.index');
    // Route::get('/admin/trainee', 'Admin\TraineeController@index')->name('admin.trainee.index');
    // Route::get('/admin/trainer', 'Admin\TrainerController@index')->name('admin.trainer.index');
    // Route::get('/admin/trainerhome', 'Admin\TrainerHomeController@index')->name('admin.trainerhome.index');



    // Route::resource('/admin/canned', 'Admin\CannedController');
    // Route::resource('/admin/classroom', 'Admin\ClassroomController');
    // Route::resource('/admin/messages', 'Admin\MessagingController');
    // Route::resource('/admin/tmessages', 'Admin\TMessagingController');
    // Route::resource('/admin/notification', 'Admin\NotificationsController');
    // Route::resource('/admin/trainee', 'Admin\TraineeController');
    // Route::resource('/admin/trainer', 'Admin\TrainerController');


    // Route::get('/admin/trainerhome', 'Admin\TrainerHomeController');


 ////////////////////
    //
    // 120 hour courses
    // 
    ////////////////////
    
    // 120 Hour Course
// home page
Route::get('/admin/onetwentyhours', 'Admin\OnetwentyhourhomepageController@index')->name('admin.onetwentyhours.index');
Route::get('/admin/onetwentyhours/home', 'Admin\OnetwentyhourhomepageController@indexHome')->name('admin.onetwentyhours.home.index');


Route::get('/admin/onetwentyhours/home', 'Admin\OnetwentyhourhomepageController@indexHome')->name('admin.onetwentyhours.home.index');

// 120 Hour Course
// unit one module one


Route::get('/admin/onetwentyhours/unit-one/module-one/section-one', 'Admin\Int120u1m1s1Controller@index')->name('admin.onetwentyhours.unit-one.module-one.section-one.index');

Route::post('/admin/onetwentyhours/unit-one/module-one/section-one', 'Admin\Int120u1m1s1Controller@store')->name('admin.onetwentyhours.unit-one.module-one.section-one.index');

Route::post('/admin/onetwentyhours/unit-one/module-one/section-one/t1', 'Admin\Int120u1m1s1t1Controller@store');
Route::post('/admin/onetwentyhours/unit-one/module-one/section-one/t2', 'Admin\Int120u1m1s1t2Controller@store');
Route::post('/admin/onetwentyhours/unit-one/module-one/section-one/t3', 'Admin\Int120u1m1s1t3Controller@store');
Route::post('/admin/onetwentyhours/unit-one/module-one/section-one/t4', 'Admin\Int120u1m1s1t4Controller@store');



// 120 Hour Course
// unit two module one
Route::get('/admin/onetwentyhours/unit-two/module-one/section-one', 'Admin\Int120u2m1s1Controller@index')->name('admin.onetwentyhours.unit-two.module-one.section-one.index');

Route::post('/admin/onetwentyhours/unit-two/module-one/section-one', 'Admin\Int120u2m1s1Controller@store@show'); 


Route::post('/admin/onetwentyhours/unit-two/module-one/section-one/t1', 'Admin\Int120u2m1s1t1Controller@store');
Route::post('/admin/onetwentyhours/unit-two/module-one/section-one/t2', 'Admin\Int120u2m1s1t2Controller@store');
Route::post('/admin/onetwentyhours/unit-two/module-one/section-one/t3', 'Admin\Int120u2m1s1t3Controller@store');
Route::post('/admin/onetwentyhours/unit-two/module-one/section-one/t4', 'Admin\Int120u2m1s1t4Controller@store');
Route::post('/admin/onetwentyhours/unit-two/module-one/section-one/t5', 'Admin\Int120u2m1s1t5Controller@store');
Route::post('/admin/onetwentyhours/unit-two/module-one/section-one/t6', 'Admin\Int120u2m1s1t6Controller@store');







//120 unit two module section two test page
Route::get('/admin/onetwentyhours/unit-two/module-one/section-two', 'Admin\Int120u2m2s1Controller@indexTwo')->name('admin.onetwentyhours.unit-two.module-one.section-two.index');

Route::post('/admin/onetwentyhours/unit-two/module-two/section-one', 'Admin\Int120u2m2s1Controller@store'); 


// 120 Hour Course
// unit two module two
Route::get('/admin/onetwentyhours/unit-two/module-two/section-one', 'Admin\Int120u2m2s1Controller@index')->name('admin.onetwentyhours.unit-two.module-two.section-one.index');

Route::post('/admin/onetwentyhours/unit-two/module-two/section-one', 'Admin\Int120u2m2s1Controller@store@show'); 


Route::post('/admin/onetwentyhours/unit-two/module-two/section-one/t1', 'Admin\Int120u2m2s1t1Controller@store');

QuickLMSbaseBuild/app/Notification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    protected $table = 'notification';

    protected $fillable = [
    	'id',
    	'NID',
    	'SID', // course_student id
    	'TRID', // course_user id
    	'TASK',
    	'NSTATUS',
    	'NDATE',
    ];
}

QuickLMSbaseBuild/app/Notifications.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notifications extends Model
{
    protected $table = 'notifications';

    protected $fillable = [
    	'id',
    	'NID',
    	'SID', // course_student id
    	'TRID', // course_user id
    	'TASK',
    	'NSTATUS',
    	'NDATE',
    ];
}

QuickLMSbaseBuild/app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Notification;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NotificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin.notification.index', compact('notification'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->except(['_token']);
 
        DB::table('notification')->insert($data);

        return redirect()->route('admin.notification.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function show(Notification $notification)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function edit(Notification $notification)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Notification $notification)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Notification  $notification
     * @return \Illuminate\Http\Response
     */
    public function destroy(Notification $notification)
    {
        //
    }
}

QuickLMSbaseBuild/app/Http/Controllers/Admin/NotificationsController.php
<?php

namespace App\Http\Controllers\Admin;

use DB;
use App\User;
use App\Notifications;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class NotificationsController extends Controller
{
    public function index(){

        $dinstinct = DB::table('users')->distinct()->first();

        $studentinfo = DB::table('users')->where('users.role_name', 'Trainee')->get();

        $notifications = DB::table('notifications')->get();
    	
        return view ('admin.notifications.index', compact('notifications', 'studentinfo', 'column', 'distinct'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin.notifications.create', compact('notificationscreate'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $data = request()->except(['_token']);

        DB::table('notifications')->insert($data);

        return redirect()->route('admin.notifications.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TraineeList  $traineeList
     * @return \Illuminate\Http\Response
     */
    public function show(Notifications $notifications)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TraineeList  $traineeList
     * @return \Illuminate\Http\Response
     */
    public function edit(Notifications $notifications)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TraineeList  $traineeList
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Notifications $notifications)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TraineeList  $traineeList
     * @return \Illuminate\Http\Response
     */
    public function destroy(Notifications $notifications)
    {
        //
    }
}

QuickLMSbaseBuild/resources/views/admin/notification/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.users.title')</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.users.store']]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', 'Email*', ['class' => 'control-label']) !!}
                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('password', 'Password*', ['class' => 'control-label']) !!}
                    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('password'))
                        <p class="help-block">
                            {{ $errors->first('password') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('role', 'Role*', ['class' => 'control-label']) !!}
                    {!! Form::select('role[]', $roles, old('role'), ['class' => 'form-control select2', 'multiple' => 'multiple', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('role'))
                        <p class="help-block">
                            {{ $errors->first('role') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

QuickLMSbaseBuild/resources/views/admin/notification/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.users.title')</h3>
    
    {!! Form::model($user, ['method' => 'PUT', 'route' => ['admin.users.update', $user->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_edit')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('name', 'Name*', ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('email', 'Email*', ['class' => 'control-label']) !!}
                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('password', 'Password', ['class' => 'control-label']) !!}
                    {!! Form::password('password', ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('password'))
                        <p class="help-block">
                            {{ $errors->first('password') }}
                        </p>
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 form-group">
                    {!! Form::label('role', 'Role*', ['class' => 'control-label']) !!}
                    {!! Form::select('role[]', $roles, old('role') ? old('role') : $user->role->pluck('id')->toArray(), ['class' => 'form-control select2', 'multiple' => 'multiple', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('role'))
                        <p class="help-block">
                            {{ $errors->first('role') }}
                        </p>
                    @endif
                </div>
            </div>
            
        </div>
    </div>

    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

QuickLMSbaseBuild/resources/views/admin/notification/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.users.title')</h3>
    @can('user_create')
    <p>
        <a href="{{ route('admin.users.create') }}" class="btn btn-success">@lang('global.app_add_new')</a>
        
    </p>
    @endcan

    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($users) > 0 ? 'datatable' : '' }} @can('user_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('user_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('global.users.fields.name')</th>
                        <th>@lang('global.users.fields.email')</th>
                        <th>@lang('global.users.fields.role')</th>
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($users) > 0)
                        @foreach ($users as $user)
                            <tr data-entry-id="{{ $user->id }}">
                                @can('user_delete')
                                    <td></td>
                                @endcan

                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    @foreach ($user->role as $singleRole)
                                        <span class="label label-info label-many">{{ $singleRole->title }}</span>
                                    @endforeach
                                </td>
                                                                <td>
                                    @can('user_view')
                                    <a href="{{ route('admin.users.show',[$user->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('user_edit')
                                    <a href="{{ route('admin.users.edit',[$user->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('user_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.users.destroy', $user->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('user_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.users.mass_destroy') }}';
        @endcan

    </script>
@endsection

QuickLMSbaseBuild/resources/views/admin/notification/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.users.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_view')
        </div>

        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('global.users.fields.name')</th>
                            <td>{{ $user->name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.users.fields.email')</th>
                            <td>{{ $user->email }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.users.fields.role')</th>
                            <td>
                                @foreach ($user->role as $singleRole)
                                    <span class="label label-info label-many">{{ $singleRole->title }}</span>
                                @endforeach
                            </td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#courses" aria-controls="courses" role="tab" data-toggle="tab">Courses</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="courses">
<table class="table table-bordered table-striped {{ count($courses) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('global.courses.fields.teachers')</th>
                        <th>@lang('global.courses.fields.title')</th>
                        <th>@lang('global.courses.fields.slug')</th>
                        <th>@lang('global.courses.fields.description')</th>
                        <th>@lang('global.courses.fields.price')</th>
                        <th>@lang('global.courses.fields.course-image')</th>
                        <th>@lang('global.courses.fields.start-date')</th>
                        <th>@lang('global.courses.fields.published')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($courses) > 0)
            @foreach ($courses as $course)
                <tr data-entry-id="{{ $course->id }}">
                    <td>
                                    @foreach ($course->teachers as $singleTeachers)
                                        <span class="label label-info label-many">{{ $singleTeachers->name }}</span>
                                    @endforeach
                                </td>
                                <td>{{ $course->title }}</td>
                                <td>{{ $course->slug }}</td>
                                <td>{!! $course->description !!}</td>
                                <td>{{ $course->price }}</td>
                                <td>@if($course->course_image)<a href="{{ asset('uploads/' . $course->course_image) }}" target="_blank"><img src="{{ asset('uploads/thumb/' . $course->course_image) }}"/></a>@endif</td>
                                <td>{{ $course->start_date }}</td>
                                <td>{{ Form::checkbox("published", 1, $course->published == 1 ? true : false, ["disabled"]) }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.courses.restore', $course->id])) !!}
                                    {!! Form::submit(trans('global.app_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.courses.perma_del', $course->id])) !!}
                                    {!! Form::submit(trans('global.app_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                                                </td>
                                @else
                                <td>
                                    @can('course_view')
                                    <a href="{{ route('admin.courses.show',[$course->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('course_edit')
                                    <a href="{{ route('admin.courses.edit',[$course->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('course_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.courses.destroy', $course->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="12">@lang('global.app_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.users.index') }}" class="btn btn-default">@lang('global.app_back_to_list')</a>
        </div>
    </div>
@stop